/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => Peekaboo
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian3 = require("obsidian");

// src/utils.ts
async function hashPassword(password) {
  const encoder = new TextEncoder();
  const data = encoder.encode(password);
  const hashBuffer = await window.crypto.subtle.digest("SHA-256", data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
}
async function verifyPassword(password, hash) {
  const calculatedHash = await hashPassword(password);
  return calculatedHash === hash;
}

// src/ribbon.ts
var import_obsidian2 = require("obsidian");

// src/modals.ts
var import_obsidian = require("obsidian");
var PasswordPromptModal = class extends import_obsidian.Modal {
  constructor(app, callback) {
    super(app);
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter password" });
    const passwordInput = new import_obsidian.TextComponent(contentEl);
    passwordInput.inputEl.type = "password";
    passwordInput.inputEl.placeholder = "Enter password";
    passwordInput.inputEl.addClass("peekaboo-inline-input-box");
    passwordInput.inputEl.addEventListener("keypress", (event) => {
      if (event.key === "Enter") {
        this.callback(passwordInput.getValue());
        this.close();
      }
    });
    contentEl.createEl("button", { text: "Submit" }).addEventListener("click", () => {
      this.callback(passwordInput.getValue());
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var IncorrectPasswordModal = class extends import_obsidian.Modal {
  constructor(app, callback) {
    super(app);
    this.callback = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Incorrect Password" });
    contentEl.createEl("p", { text: "The password you entered is incorrect." });
    contentEl.createEl("button", { text: "OK" }).addEventListener("click", () => {
      this.callback();
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var HideSpecifyFileModal = class extends import_obsidian.Modal {
  constructor(app, resolve) {
    super(app);
    this.resolve = resolve;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter file path" });
    const inputEl = contentEl.createEl("input", { type: "text", cls: "peekaboo-single-line-input-box" });
    inputEl.focus();
    const submit = () => {
      this.resolve(inputEl.value);
      this.close();
    };
    inputEl.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        submit();
      }
    });
    const buttonContainer = contentEl.createDiv({ cls: "peekaboo-single-line-button-container" });
    const submitBtn = buttonContainer.createEl("button", { text: "Submit", cls: "peekaboo-single-line-button" });
    submitBtn.onclick = submit;
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel", cls: "peekaboo-single-line-button" });
    cancelBtn.onclick = () => {
      this.resolve(null);
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/hider.ts
function generateSelectors(paths) {
  return paths.map((path) => {
    path = path.replace(/^\/|\/$/g, "");
    if (path.includes("*")) {
      if (path.length == 1) {
        return [];
      } else if (!path.endsWith("*")) {
        return [];
      } else {
        return [`.nav-file-title[data-path^="${path.replace(/.$/, "")}"]`];
      }
    } else {
      return [
        `.nav-folder-title[data-path="${path}"]`,
        `.nav-folder-title[data-path^="${path}/"]`,
        `.nav-file-title[data-path="${path}"]`,
        `.nav-file-title[data-path^="${path}."]`,
        `.nav-file-title[data-path^="${path}/"]`
      ];
    }
  }).flat().join(", ");
}
function notesSelectors(paths) {
  return paths.map((path) => {
    path = path.replace(/^\/|\/$/g, "");
    if (path.includes("*")) {
      if (path.length == 1) {
        return [];
      } else if (!path.endsWith("*")) {
        return [];
      } else {
        return [`.nav-file-title[data-path^="${path.replace(/.$/, "")}"]`];
      }
    } else {
      return [
        `.nav-file-title[data-path="${path}"]`,
        `.nav-file-title[data-path^="${path}."]`
      ];
    }
  }).flat().join(", ");
}
function applyHiddenFolders(plugin) {
  if (plugin.settings.currentHiddenFolders.length === 0) {
    plugin.styleEl.textContent = "";
    return;
  }
  const hiddenSelectors = generateSelectors(plugin.settings.currentHiddenFolders);
  const exceptionSelectors = notesSelectors(plugin.settings.currentExceptionFiles);
  plugin.styleEl.textContent = hiddenSelectors ? `${hiddenSelectors} { display: none !important; } ${exceptionSelectors} { display: block !important; }` : "";
  const head = document.head;
  head.removeChild(plugin.styleEl);
  head.appendChild(plugin.styleEl);
}
function updateExceptionFiles(plugin, filePath) {
  if (!plugin.settings.currentExceptionFiles.includes(filePath)) {
    plugin.settings.currentExceptionFiles.push(filePath);
  }
  plugin.saveSettings();
  plugin.applyHiddenFolders();
}
async function showAllConfiguredFiles(plugin) {
  plugin.settings.currentHiddenFolders = [];
  plugin.settings.configuredExceptionFiles = [];
  await plugin.saveSettings();
  plugin.applyHiddenFolders();
}
async function hideAllConfiguredFiles(plugin) {
  plugin.settings.currentHiddenFolders = [...plugin.settings.configuredHiddenFolders];
  plugin.settings.currentExceptionFiles = [...plugin.settings.configuredExceptionFiles];
  await plugin.saveSettings();
  plugin.applyHiddenFolders();
}
async function toggleConfiguredFoldersVisibility(plugin) {
  if (plugin.settings.currentHiddenFolders.length > 0) {
    plugin.settings.currentHiddenFolders = [];
    plugin.settings.currentExceptionFiles = [];
  } else {
    plugin.settings.currentHiddenFolders = [...plugin.settings.configuredHiddenFolders];
    plugin.settings.currentExceptionFiles = [...plugin.settings.configuredExceptionFiles];
  }
  await plugin.saveSettings();
  plugin.applyHiddenFolders();
  updateRibbonIcon(plugin);
}
function showSpecifiedFile(plugin, filePath) {
  plugin.settings.currentHiddenFolders = plugin.settings.currentHiddenFolders.filter((path) => path !== filePath);
  plugin.applyHiddenFolders();
}
async function promptForFilePath(plugin, callback) {
  const modal = new HideSpecifyFileModal(plugin.app, callback);
  modal.open();
}

// src/ribbon.ts
function updateRibbonIcon(plugin) {
  if (!plugin.ribbonIconEl) {
    plugin.ribbonIconEl = plugin.addRibbonIcon("eye", "Peekaboo", () => {
      new RibbonCommandModal(plugin.app, plugin).open();
    });
  }
  if (plugin.settings.currentHiddenFolders.length > 0) {
    plugin.ribbonIconEl.setAttribute("aria-label", "Peekaboo");
    (0, import_obsidian2.setIcon)(plugin.ribbonIconEl, "eye-off");
  } else {
    plugin.ribbonIconEl.setAttribute("aria-label", "Peekaboo");
    (0, import_obsidian2.setIcon)(plugin.ribbonIconEl, "eye");
  }
}
var RibbonCommandModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  createButton(container, text, onClick) {
    const buttonWrapper = container.createDiv({ cls: "peekaboo-ribbon-commands-button-container" });
    const button = buttonWrapper.createEl("button", { text });
    button.addEventListener("click", onClick);
    button.addClass("peekaboo-ribbon-commands-button");
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("peekaboo-ribbon-commands-container");
    contentEl.createEl("h2", { text: "Peekaboo" });
    this.createButton(contentEl, "Toggle configured files visibility", async () => {
      this.close();
      this.plugin.handlePasswordPrompt(async (password) => {
        if (await this.plugin.verifyPassword(password)) {
          await toggleConfiguredFoldersVisibility(this.plugin);
          updateRibbonIcon(this.plugin);
        } else {
          this.plugin.showIncorrectPasswordDialog(() => this.plugin.handlePasswordPrompt(async (password2) => {
            if (await this.plugin.verifyPassword(password2)) {
              await toggleConfiguredFoldersVisibility(this.plugin);
              updateRibbonIcon(this.plugin);
            }
          }));
        }
      });
    });
    this.createButton(contentEl, "Show specified note", async () => {
      this.close();
      this.plugin.handlePasswordPrompt(async (password) => {
        if (await this.plugin.verifyPassword(password)) {
          promptForFilePath(this.plugin, (filePath) => {
            if (filePath) {
              showSpecifiedFile(this.plugin, filePath);
              updateExceptionFiles(this.plugin, filePath);
              updateRibbonIcon(this.plugin);
            }
          });
        } else {
          this.plugin.showIncorrectPasswordDialog(() => this.plugin.handlePasswordPrompt(async (password2) => {
            if (await this.plugin.verifyPassword(password2)) {
              promptForFilePath(this.plugin, (filePath) => {
                if (filePath) {
                  showSpecifiedFile(this.plugin, filePath);
                  updateExceptionFiles(this.plugin, filePath);
                  updateRibbonIcon(this.plugin);
                }
              });
            }
          }));
        }
      });
    });
    this.createButton(contentEl, "Show all configured files", async () => {
      this.close();
      this.plugin.handlePasswordPrompt(async (password) => {
        if (await this.plugin.verifyPassword(password)) {
          await showAllConfiguredFiles(this.plugin);
          updateRibbonIcon(this.plugin);
        } else {
          this.plugin.showIncorrectPasswordDialog(() => this.plugin.handlePasswordPrompt(async (password2) => {
            if (await this.plugin.verifyPassword(password2)) {
              await showAllConfiguredFiles(this.plugin);
              updateRibbonIcon(this.plugin);
            }
          }));
        }
      });
    });
    this.createButton(contentEl, "Hide all configured files", async () => {
      this.close();
      this.plugin.handlePasswordPrompt(async (password) => {
        if (await this.plugin.verifyPassword(password)) {
          await hideAllConfiguredFiles(this.plugin);
          updateRibbonIcon(this.plugin);
        } else {
          this.plugin.showIncorrectPasswordDialog(() => this.plugin.handlePasswordPrompt(async (password2) => {
            if (await this.plugin.verifyPassword(password2)) {
              await hideAllConfiguredFiles(this.plugin);
              updateRibbonIcon(this.plugin);
            }
          }));
        }
      });
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings.ts
var DEFAULT_SETTINGS = {
  passwordHash: "",
  configuredHiddenFolders: [],
  currentHiddenFolders: [],
  hideRibbonIcon: false,
  configuredExceptionFiles: [],
  currentExceptionFiles: []
};
async function loadSettings(plugin) {
  return Object.assign({}, DEFAULT_SETTINGS, await plugin.loadData());
}
async function saveSettings(plugin) {
  await plugin.saveData(plugin.settings);
}
var PeekabooSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Password").setDesc("Set a password to protect the visibility of your files.").addButton((button) => {
      button.setButtonText("Set password").onClick(async () => {
        this.plugin.promptForPassword(async (password) => {
          this.plugin.settings.passwordHash = await hashPassword(password);
          await this.plugin.saveSettings();
        });
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Configured hidden files").setDesc("Manage configure hidden folders and notes, one per line.").addButton((button) => {
      button.setButtonText("Manage hidden items").onClick(() => {
        if (!this.plugin.settings.passwordHash) {
          new import_obsidian3.Notice("Please set a password first.");
          new SetPasswordPromptModal(this.app).open();
          return;
        }
        const promptForPassword = async () => {
          this.plugin.handlePasswordPrompt(async (password) => {
            if (await this.plugin.verifyPassword(password)) {
              new HiddenFoldersModal(this.app, this.plugin).open();
            } else {
              this.plugin.showIncorrectPasswordDialog(promptForPassword);
            }
          });
        };
        promptForPassword();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Configured exception files").setDesc("Manage configured exception notes, one per line. Notes only (folders not supported)").addButton((button) => {
      button.setButtonText("Manage exception items").onClick(() => {
        if (!this.plugin.settings.passwordHash) {
          new import_obsidian3.Notice("Please set a password first.");
          new SetPasswordPromptModal(this.app).open();
          return;
        }
        const promptForPassword = async () => {
          this.plugin.handlePasswordPrompt(async (password) => {
            if (await this.plugin.verifyPassword(password)) {
              new ExceptionFilesModal(this.app, this.plugin).open();
            } else {
              this.plugin.showIncorrectPasswordDialog(promptForPassword);
            }
          });
        };
        promptForPassword();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Tips:").setDesc("1. About 'Configured exception files': For example, when you want to show a note within a hidden folder...");
    containerEl.createEl("div").createEl("p", { text: "2. Enhance security with 'Excluded files': To prevent hidden files from appearing in Search, Graph View, etc., configure 'Excluded files' under Options > Files and Links > Excluded files.", cls: "peekaboo-tips" });
  }
};
var SetPasswordPromptModal = class extends import_obsidian3.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Please set a password first." });
    const okBtn = contentEl.createEl("button", { text: "OK" });
    okBtn.onclick = () => {
      this.close();
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var HiddenFoldersModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Manage configured hidden folders and files" });
    const textArea = contentEl.createEl("textarea", {
      placeholder: "Enter folders or files to hide, one per line",
      cls: "peekaboo-textarea"
    });
    textArea.value = this.plugin.settings.configuredHiddenFolders.join("\n");
    const buttonContainer = contentEl.createDiv({ cls: "peekaboo-single-line-button-container" });
    buttonContainer.createEl("button", { text: "Save" }).addEventListener("click", async () => {
      const newHiddenFolders = textArea.value.split("\n").map((item) => item.trim()).filter((item) => item);
      this.plugin.settings.configuredHiddenFolders = newHiddenFolders;
      this.plugin.settings.currentHiddenFolders = newHiddenFolders;
      this.plugin.settings.currentExceptionFiles = [...this.plugin.settings.configuredExceptionFiles];
      await saveSettings(this.plugin);
      applyHiddenFolders(this.plugin);
      updateRibbonIcon(this.plugin);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ExceptionFilesModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Manage configured exception folders and files" });
    const textArea = contentEl.createEl("textarea", {
      placeholder: "Enter folders or files to exclude, one per line",
      cls: "peekaboo-textarea"
    });
    textArea.value = this.plugin.settings.configuredExceptionFiles.join("\n");
    const buttonContainer = contentEl.createDiv({ cls: "peekaboo-single-line-button-container" });
    buttonContainer.createEl("button", { text: "Save" }).addEventListener("click", async () => {
      const newExceptionFiles = textArea.value.split("\n").map((item) => item.trim()).filter((item) => item);
      this.plugin.settings.configuredExceptionFiles = newExceptionFiles;
      this.plugin.settings.currentExceptionFiles = newExceptionFiles;
      await saveSettings(this.plugin);
      applyHiddenFolders(this.plugin);
      updateRibbonIcon(this.plugin);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/commands.ts
var import_obsidian4 = require("obsidian");
function registerCommands(plugin) {
  plugin.addCommand({
    id: "toggle-configured-files-visibility",
    name: "Toggle Configured Files Visibility",
    callback: () => {
      if (!plugin.settings.passwordHash) {
        new import_obsidian4.Notice("Please set a password first.");
        return;
      }
      const promptForPassword = async () => {
        plugin.handlePasswordPrompt(async (password) => {
          if (await plugin.verifyPassword(password)) {
            toggleConfiguredFoldersVisibility(plugin);
            updateRibbonIcon(plugin);
          } else {
            plugin.showIncorrectPasswordDialog(promptForPassword);
          }
        });
      };
      promptForPassword();
    }
  });
  plugin.addCommand({
    id: "show-specified-file",
    name: "Show Specified File",
    callback: () => {
      if (!plugin.settings.passwordHash) {
        new import_obsidian4.Notice("Please set a password first.");
        return;
      }
      const promptForPassword = async () => {
        plugin.handlePasswordPrompt(async (password) => {
          if (await plugin.verifyPassword(password)) {
            promptForFilePath(plugin, (filePath) => {
              if (filePath) {
                showSpecifiedFile(plugin, filePath);
                updateRibbonIcon(plugin);
              }
            });
          } else {
            plugin.showIncorrectPasswordDialog(promptForPassword);
          }
        });
      };
      promptForPassword();
    }
  });
  plugin.addCommand({
    id: "show-all-configured-files",
    name: "Show all configured files",
    callback: () => plugin.handlePasswordPrompt(async (password) => {
      if (await plugin.verifyPassword(password)) {
        await showAllConfiguredFiles(plugin);
        updateRibbonIcon(plugin);
      } else {
        plugin.showIncorrectPasswordDialog(() => plugin.handlePasswordPrompt(async (password2) => {
          if (await plugin.verifyPassword(password2)) {
            await showAllConfiguredFiles(plugin);
            updateRibbonIcon(plugin);
          }
        }));
      }
    })
  });
  plugin.addCommand({
    id: "hide-all-configured-files",
    name: "Hide all configured files",
    callback: () => plugin.handlePasswordPrompt(async (password) => {
      if (await plugin.verifyPassword(password)) {
        await hideAllConfiguredFiles(plugin);
        updateRibbonIcon(plugin);
      } else {
        plugin.showIncorrectPasswordDialog(() => plugin.handlePasswordPrompt(async (password2) => {
          if (await plugin.verifyPassword(password2)) {
            await hideAllConfiguredFiles(plugin);
            updateRibbonIcon(plugin);
          }
        }));
      }
    })
  });
  plugin.addCommand({
    id: "create-folder",
    name: "Create folder",
    callback: () => createFolder()
  });
}
var CreateFolderModal = class extends import_obsidian4.Modal {
  constructor(app) {
    super(app);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Enter Folder Name" });
    const inputEl = contentEl.createEl("input", { type: "text", cls: "peekaboo-single-line-input-box" });
    inputEl.addEventListener("input", (e) => {
      this.folderName = e.target.value;
    });
    inputEl.addEventListener("keypress", (e) => {
      if (e.key === "Enter") {
        this.resolve(this.folderName);
        this.close();
      }
    });
    const buttonContainer = contentEl.createDiv({ cls: "peekaboo-single-line-button-container" });
    buttonContainer.createEl("button", { text: "Create", cls: "peekaboo-single-line-button" }).addEventListener("click", () => {
      this.resolve(this.folderName);
      this.close();
    });
    buttonContainer.createEl("button", { text: "Cancel", cls: "peekaboo-single-line-button" }).addEventListener("click", () => {
      this.resolve(null);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  open() {
    return new Promise((resolve) => {
      this.resolve = resolve;
      super.open();
    });
  }
};
async function createFolder() {
  const folderName = await new CreateFolderModal(this.app).open();
  if (folderName) {
    try {
      await this.app.vault.createFolder(folderName);
      new import_obsidian4.Notice(`Folder '${folderName}' created.`);
    } catch (error) {
      new import_obsidian4.Notice(`Failed to create folder '${folderName}': ${error.message}`);
    }
  }
}

// src/main.ts
var Peekaboo = class extends import_obsidian5.Plugin {
  async onload() {
    console.log("Loading Peekaboo plugin");
    await this.loadSettings();
    this.addSettingTab(new PeekabooSettingTab(this.app, this));
    registerCommands(this);
    this.styleEl = document.createElement("style");
    document.head.appendChild(this.styleEl);
    this.applyHiddenFolders();
    updateRibbonIcon(this);
  }
  onunload() {
    document.head.removeChild(this.styleEl);
    if (this.ribbonIconEl) {
      this.ribbonIconEl.remove();
    }
  }
  async loadSettings() {
    this.settings = await loadSettings(this);
  }
  async saveSettings() {
    await saveSettings(this);
  }
  applyHiddenFolders() {
    applyHiddenFolders(this);
  }
  handlePasswordPrompt(callback) {
    const promptForPassword = () => {
      this.promptForPassword(async (password) => {
        if (await this.verifyPassword(password)) {
          callback(password);
        } else {
          this.showIncorrectPasswordDialog(promptForPassword);
        }
      });
    };
    promptForPassword();
  }
  promptForPassword(callback) {
    const modal = new PasswordPromptModal(this.app, callback);
    modal.open();
  }
  showIncorrectPasswordDialog(callback) {
    const modal = new IncorrectPasswordModal(this.app, callback);
    modal.open();
  }
  async verifyPassword(password) {
    return verifyPassword(password, this.settings.passwordHash);
  }
};
